# Generated by Django 4.1.7 on 2023-02-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
